---
title: "HW2_leaflet"
author: "Nicole Li"
date: "October 4, 2019"
output: html_document
---

```{r setup, include=FALSE}
require(rgdal)
require(leaflet)
require(leaflet.extras)
require(dplyr)
require(readxl)
require(stringr)
```

## Loading in all datasets from data.gov
#https://catalog.data.gov/dataset/loudoun-stormwater-pipes-5afb6
```{r} 
fire<- readOGR("fire.geojson")   
pipe<- readOGR("pipes.geojson")
realestate<- readOGR("realestate.geojson")
```

#Looking at the attributes and statistics of data
```{r pressure, echo=FALSE}
#plot(fire)
#summary(fire)
#plot(pipes)
#summary(pipes)
#plot(realestate)
#summary(realestate)

```

#Map of Fires Incidents
```{r}
#Fire incidents colored by different Years 2015-2019
firepalette<- colorFactor(palette = "YlOrRd", domain = fire$year)

leaflet() %>% 
  # creating Basemaps
  addProviderTiles("Stamen.Terrain") %>%
  #creating markers for the fire incidents location
  addCircleMarkers(data = fire, color = ~firepalette(year), radius = 3, fillOpacity = 0.2,clusterOptions = markerClusterOptions()) %>% 
  #adding legend showing colors associated with the year
  addLegend(position = "topright" , pal = firepalette, values = fire$year, title = "Year")
```

#Map of stormwater pipes
```{r}
#Distinguishing Pipes by making the bigger piepes greener
pipepalette<- colorNumeric(palette = "Spectral", domain = pipe$Pipe_Diam, reverse= TRUE)

leaflet(data=pipe) %>% 
  # creating base map
  addProviderTiles("Stamen.Toner") %>%
  # creating lines for the location of the pipes
  addPolylines(color = ~pipepalette(Pipe_Diam))
```


#Creating map of real estate subdivision
```{r}
leaflet() %>%
  # creating Basemaps
  addProviderTiles("Stamen.Toner", group = "Toner") %>%
  addProviderTiles("Stamen.Terrain", group = "Terrain") %>%
  addProviderTiles("Stamen.TonerLite", group = "Toner Lite")%>%
  # Layers control
  addLayersControl(
    baseGroups = c("Toner", "Terrain", "Toner Lite"),
    options = layersControlOptions(collapsed = FALSE)) %>%
  addPolygons(data = realestate, group = c("Toner","Terrain", "Toner Lite"))

  
```


